language: android
dist: trusty
jdk: oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-29

script:
  - ./gradlew build
